"""check_for_pending_model_changes

Revision ID: da250e002da0
Revises: aa5a5e196132
Create Date: 2025-06-01 11:23:34.243362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da250e002da0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('author_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('cover_url', sa.TEXT(), nullable=True),
                    sa.Column('description', sa.TEXT(), nullable=True),
                    sa.Column('long_description', sa.TEXT(), nullable=True),
                    sa.Column('reading_time_minutes',
                              sa.Integer(), nullable=True),
                    sa.Column('age_min', sa.Integer(), nullable=True),
                    sa.Column('age_max', sa.Integer(), nullable=True),
                    sa.Column('publisher', sa.String(
                        length=255), nullable=True),
                    sa.Column('publish_date', sa.Date(), nullable=True),
                    sa.Column('is_premium', sa.Boolean(), nullable=False),
                    sa.Column('is_free', sa.Boolean(), nullable=False),
                    sa.Column('popularity_score',
                              sa.Integer(), nullable=False),
                    sa.Column('total_pages', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('themes',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.TEXT(), nullable=True),
                    sa.Column('icon_identifier', sa.String(
                        length=100), nullable=True),
                    sa.Column('age_range_display', sa.String(
                        length=50), nullable=True),
                    sa.Column('category', sa.Enum('SELF', 'OTHERS', 'WORLD',
                                                  'THINKING', name='theme_category_enum'), nullable=False),
                    sa.Column('cover_image_url', sa.TEXT(), nullable=True),
                    sa.Column('question_prompt', sa.TEXT(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('hashed_password', sa.TEXT(), nullable=False),
                    sa.Column('avatar_url', sa.TEXT(), nullable=True),
                    sa.Column('tier', sa.Enum('FREE', 'PREMIUM', 'CREATOR',
                                              'ADMIN', name='user_tier_enum'), nullable=False),
                    sa.Column('introduction', sa.TEXT(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('book_pages',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('book_id', sa.UUID(), nullable=False),
                    sa.Column('page_number', sa.Integer(), nullable=False),
                    sa.Column('image_url', sa.TEXT(), nullable=False),
                    sa.Column('audio_url', sa.TEXT(), nullable=True),
                    sa.Column('question_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['book_id'], ['books.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('book_themes',
                    sa.Column('book_id', sa.UUID(), nullable=False),
                    sa.Column('theme_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['book_id'], ['books.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['theme_id'], ['themes.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('book_id', 'theme_id')
                    )
    op.create_table('book_toc_items',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('book_id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('page_number', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['book_id'], ['books.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('children',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('avatar_url', sa.TEXT(), nullable=True),
                    sa.Column('interests', postgresql.ARRAY(
                        sa.TEXT()), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('reviews',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('book_id', sa.UUID(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column('text', sa.TEXT(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['book_id'], ['books.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_favorites',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('book_id', sa.UUID(), nullable=False),
                    sa.Column('favorited_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['book_id'], ['books.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'book_id')
                    )
    op.create_table('user_settings',
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('notify_new_recommendations',
                              sa.Boolean(), nullable=False),
                    sa.Column('notify_child_progress_updates',
                              sa.Boolean(), nullable=False),
                    sa.Column('notify_platform_announcements',
                              sa.Boolean(), nullable=False),
                    sa.Column('notify_weekly_summary',
                              sa.Boolean(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    op.create_table('learning_activities',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('child_id', sa.UUID(), nullable=True),
                    sa.Column('activity_type', sa.Enum('BOOK_READ_COMPLETED', 'QUESTION_ANSWERED', 'BADGE_EARNED',
                                                       'NOTE_TAKEN', 'DISCUSSION_POSTED', name='activity_type_enum'), nullable=False),
                    sa.Column('description', sa.TEXT(), nullable=False),
                    sa.Column('related_entity_id', sa.UUID(), nullable=True),
                    sa.Column('related_link', sa.TEXT(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['child_id'], ['children.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_book_progress',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('child_id', sa.UUID(), nullable=True),
                    sa.Column('book_id', sa.UUID(), nullable=False),
                    sa.Column('current_page', sa.Integer(), nullable=False),
                    sa.Column('last_read_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['book_id'], ['books.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['child_id'], ['children.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_book_bookmarks',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('progress_id', sa.UUID(), nullable=False),
                    sa.Column('page_number', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['progress_id'], ['user_book_progress.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_book_notes',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('progress_id', sa.UUID(), nullable=False),
                    sa.Column('page_number', sa.Integer(), nullable=False),
                    sa.Column('text', sa.TEXT(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['progress_id'], ['user_book_progress.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_book_notes')
    op.drop_table('user_book_bookmarks')
    op.drop_table('user_book_progress')
    op.drop_table('learning_activities')
    op.drop_table('user_settings')
    op.drop_table('user_favorites')
    op.drop_table('reviews')
    op.drop_table('children')
    op.drop_table('book_toc_items')
    op.drop_table('book_themes')
    op.drop_table('book_pages')
    op.drop_table('users')
    op.drop_table('themes')
    op.drop_table('books')
    # ### end Alembic commands ###
